### ISSUE TITLE
4_Python_Functions.ipynb doesn't start in colab

### ISSUE THREAD

**Issue by mmotl** [neuefische/ds-welcome-package#19]
Hi together,

though you can work with the entry otherwise, of course,
since there is so much work and effort in it _(thanks at this place!)_, I wanted to point out that **the jupyter notebook "4_Python_Functions.ipynb"**
[https://github.com/neuefische/ds-welcome-package/blob/main/programming/4_Python_Functions.ipynb](https://github.com/neuefische/ds-welcome-package/blob/main/programming/4_Python_Functions.ipynb)
**is not starting in google colab** - maybe due to some authorisation issue.

Sorry for being pedantic - and if I formally messed up this issue contribution, let me know. It's my first. :)
Looking forward to meet all of you soon,
regards,
Matthias

**Comment by rogall-e** [comment]
Hi Matthias,

thank you for your feedback! It should work now.
 
Cheers,
Eike

**Comment by mmotl** [comment]
Hi Eike,

yes, I can confirm this. Thank you for the fast response!

Regards,
Matthias
